// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// squash_interval_set
NumericMatrix squash_interval_set(NumericMatrix x, bool na_rm);
RcppExport SEXP _intervalset_squash_interval_set(SEXP xSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(squash_interval_set(x, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// union_interval_set
NumericMatrix union_interval_set(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _intervalset_union_interval_set(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(union_interval_set(x, y));
    return rcpp_result_gen;
END_RCPP
}
// compliment_interval_set
NumericMatrix compliment_interval_set(NumericMatrix x);
RcppExport SEXP _intervalset_compliment_interval_set(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(compliment_interval_set(x));
    return rcpp_result_gen;
END_RCPP
}
// inf
NumericVector inf();
RcppExport SEXP _intervalset_inf() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(inf());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intervalset_squash_interval_set", (DL_FUNC) &_intervalset_squash_interval_set, 2},
    {"_intervalset_union_interval_set", (DL_FUNC) &_intervalset_union_interval_set, 2},
    {"_intervalset_compliment_interval_set", (DL_FUNC) &_intervalset_compliment_interval_set, 1},
    {"_intervalset_inf", (DL_FUNC) &_intervalset_inf, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_intervalset(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
