// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_intersect_interval_sets
List cpp_intersect_interval_sets(const List& x, const List& y);
RcppExport SEXP _intervalset_cpp_intersect_interval_sets(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const List& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_intersect_interval_sets(x, y));
    return rcpp_result_gen;
END_RCPP
}
// intersect_cpp
List intersect_cpp(const IntegerVector& x_size, const NumericVector& x_starts, const NumericVector& x_ends, const IntegerVector& y_size, const NumericVector& y_starts, const NumericVector& y_ends);
RcppExport SEXP _intervalset_intersect_cpp(SEXP x_sizeSEXP, SEXP x_startsSEXP, SEXP x_endsSEXP, SEXP y_sizeSEXP, SEXP y_startsSEXP, SEXP y_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_size(x_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_starts(x_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_ends(x_endsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y_size(y_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_starts(y_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_ends(y_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(intersect_cpp(x_size, x_starts, x_ends, y_size, y_starts, y_ends));
    return rcpp_result_gen;
END_RCPP
}
// span_set_only_cpp
List span_set_only_cpp(const IntegerVector& x_size, const NumericVector& x_starts, const NumericVector& x_ends, const IntegerVector& y_size, const NumericVector& y_starts, const NumericVector& y_ends);
RcppExport SEXP _intervalset_span_set_only_cpp(SEXP x_sizeSEXP, SEXP x_startsSEXP, SEXP x_endsSEXP, SEXP y_sizeSEXP, SEXP y_startsSEXP, SEXP y_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_size(x_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_starts(x_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_ends(x_endsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y_size(y_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_starts(y_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_ends(y_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(span_set_only_cpp(x_size, x_starts, x_ends, y_size, y_starts, y_ends));
    return rcpp_result_gen;
END_RCPP
}
// do_nothing_cpp
List do_nothing_cpp(const IntegerVector& x_size, const NumericVector& x_starts, const NumericVector& x_ends, const IntegerVector& y_size, const NumericVector& y_starts, const NumericVector& y_ends);
RcppExport SEXP _intervalset_do_nothing_cpp(SEXP x_sizeSEXP, SEXP x_startsSEXP, SEXP x_endsSEXP, SEXP y_sizeSEXP, SEXP y_startsSEXP, SEXP y_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_size(x_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_starts(x_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_ends(x_endsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y_size(y_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_starts(y_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_ends(y_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(do_nothing_cpp(x_size, x_starts, x_ends, y_size, y_starts, y_ends));
    return rcpp_result_gen;
END_RCPP
}
// span_buffer_only_cpp
List span_buffer_only_cpp(const IntegerVector& x_size, const NumericVector& x_starts, const NumericVector& x_ends, const IntegerVector& y_size, const NumericVector& y_starts, const NumericVector& y_ends);
RcppExport SEXP _intervalset_span_buffer_only_cpp(SEXP x_sizeSEXP, SEXP x_startsSEXP, SEXP x_endsSEXP, SEXP y_sizeSEXP, SEXP y_startsSEXP, SEXP y_endsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type x_size(x_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_starts(x_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_ends(x_endsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type y_size(y_sizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_starts(y_startsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_ends(y_endsSEXP);
    rcpp_result_gen = Rcpp::wrap(span_buffer_only_cpp(x_size, x_starts, x_ends, y_size, y_starts, y_ends));
    return rcpp_result_gen;
END_RCPP
}
// listof_dbl_unchop_cpp
NumericVector listof_dbl_unchop_cpp(const List& chopped);
RcppExport SEXP _intervalset_listof_dbl_unchop_cpp(SEXP choppedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type chopped(choppedSEXP);
    rcpp_result_gen = Rcpp::wrap(listof_dbl_unchop_cpp(chopped));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_intervalset_cpp_intersect_interval_sets", (DL_FUNC) &_intervalset_cpp_intersect_interval_sets, 2},
    {"_intervalset_intersect_cpp", (DL_FUNC) &_intervalset_intersect_cpp, 6},
    {"_intervalset_span_set_only_cpp", (DL_FUNC) &_intervalset_span_set_only_cpp, 6},
    {"_intervalset_do_nothing_cpp", (DL_FUNC) &_intervalset_do_nothing_cpp, 6},
    {"_intervalset_span_buffer_only_cpp", (DL_FUNC) &_intervalset_span_buffer_only_cpp, 6},
    {"_intervalset_listof_dbl_unchop_cpp", (DL_FUNC) &_intervalset_listof_dbl_unchop_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_intervalset(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
