# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_intersect_interval_sets <- function(x, y) {
    .Call(`_intervalset_cpp_intersect_interval_sets`, x, y)
}

intersect_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_intervalset_intersect_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

span_set_only_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_intervalset_span_set_only_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

do_nothing_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_intervalset_do_nothing_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

span_buffer_only_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_intervalset_span_buffer_only_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

listof_dbl_unchop_cpp <- function(chopped) {
    .Call(`_intervalset_listof_dbl_unchop_cpp`, chopped)
}

