# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subset_cpp <- function(sizes, starts, ends, indices) {
    .Call(`_intervalset_subset_cpp`, sizes, starts, ends, indices)
}

intersect_v0_cpp <- function(x, y) {
    .Call(`_intervalset_intersect_v0_cpp`, x, y)
}

squash_v0_cpp <- function(x) {
    .Call(`_intervalset_squash_v0_cpp`, x)
}

listof_dbl_unchop_cpp <- function(chopped) {
    .Call(`_intervalset_listof_dbl_unchop_cpp`, chopped)
}

intersect_v1_cpp <- function(x_size, x_starts, x_ends, y_size, y_starts, y_ends) {
    .Call(`_intervalset_intersect_v1_cpp`, x_size, x_starts, x_ends, y_size, y_starts, y_ends)
}

squash_v1_cpp <- function(starts, ends) {
    .Call(`_intervalset_squash_v1_cpp`, starts, ends)
}

